<a href="https://colab.research.google.com/github/Sunkara-saivardhan/ANN-Iris-Flower-Classification/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#keras
#tensorflow

In [ ]:
#import required libraries
import keras #library of neural networks
import pandas as pd #loading data in table form
import seaborn as sns #visulization
import matplotlib.pyplot as plt #visulization
import numpy as np #mathematical operations
from sklearn.preprocessing import normalize #machine learning algorithm library
from sklearn.model_selection import train_test_split

In [ ]:
#loading the data
data= pd.read_csv("/content/iris.csv")
data.head()


,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [ ]:
data.shape

(150, 5)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
data.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [ ]:
print(data.head(10)) #first 10 samples of the dataset
print(data.tail(10)) #"last 10 samples of the dataset

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8   

In [ ]:
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
data.isnull().sum()

,0
sepal_length,0
sepal_width,0
petal_length,0
petal_width,0
species,0


In [ ]:
data.loc[data['species']=='setosa','species']=0
data.loc[data['species']=='versicolor','species']=1
data.loc[data['species']=='virginica','species']=2
print(data.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0


In [ ]:
#shiffling data because our data has 150 rows in that first 50 species are  setosa and next 50 versicolor and last 50 are virginica is not good to train the model
data=data.loc[np.random.permutation(len(data))]
data.head()

,sepal_length,sepal_width,petal_length,petal_width,species
41,4.5,2.3,1.3,0.3,0
119,6.0,2.2,5.0,1.5,2
137,6.4,3.1,5.5,1.8,2
80,5.5,2.4,3.8,1.1,1
86,6.7,3.1,4.7,1.5,1


In [ ]:
x=data.drop(columns=['species'])
y=data['species']
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [ ]:
y_train

,species
10,0
97,1
31,0
75,1
82,1
...,...
37,0
133,2
55,1
79,1


In [ ]:
#neural network modules
from keras.models import Sequential
from keras.layers import Dense, Activation
#from keras.utilts import np_utilts
import tensorflow as tf

In [ ]:
#change label to one hot encoder
'''
[0]->[1,0,0]
[1]->[0,1,0]
[2]->[0,0,1]
'''
y_train=tf.keras.utils.to_categorical(y_train,num_classes=3)
y_test=tf.keras.utils.to_categorical(y_test,num_classes=3)
print("shape of y_train",y_train.shape)
print("shape of y_test",y_test.shape)

shape of y_train (120, 3)
shape of y_test (30, 3)


In [ ]:
#multi-class classfication
#define keras model

model=Sequential()

model.add(Dense(32, input_dim=4, activation='relu'))# 1 hidden layers and input_dim represent how many neurons in input layer
model.add(Dense(64,  activation='relu'))# 2 hidden layer
model.add(Dense(128, activation='relu'))# 3 hidden layer

model.add(Dense(3, activation='softmax'))# output layer

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(
    loss='categorical_crossentropy', #error
    optimizer='adam', #gradient decent
    metrics=['accuracy'] #accuracy
)

In [ ]:
#training the data
model.fit(X_train,y_train,
    validation_data=(X_test, y_test),
    batch_size=30,
    epochs=30)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.3417 - loss: 1.1265 - val_accuracy: 0.2667 - val_loss: 1.0960
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3500 - loss: 1.0183 - val_accuracy: 0.2667 - val_loss: 1.0040
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.4833 - loss: 0.9475 - val_accuracy: 0.7333 - val_loss: 0.8985
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6500 - loss: 0.8742 - val_accuracy: 0.7333 - val_loss: 0.8242
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6500 - loss: 0.8127 - val_accuracy: 0.7333 - val_loss: 0.7507
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6917 - loss: 0.7492 - val_accuracy: 0.8667 - val_loss: 0.6839
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8917 - loss: 0.6955 - val_accuracy: 0.9333 - val_loss: 0.6183
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8500 - loss: 0.6398 - val_accuracy: 0.7667 - val_loss: 0.5516


In [ ]:
y_pred = model.predict(X_test)
print("accuracy",y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
accuracy [[9.94033933e-01 5.94191998e-03 2.41261987e-05]
 [9.07819776e-04 4.90632921e-01 5.08459270e-01]
 [9.88720298e-01 1.11727044e-02 1.07032844e-04]
 [9.87077892e-01 1.28137134e-02 1.08445063e-04]
 [4.78847977e-03 8.30199599e-01 1.65011913e-01]
 [1.02808103e-02 7.95176268e-01 1.94543034e-01]
 [3.45169945e-04 4.83452588e-01 5.16202152e-01]
 [1.39134601e-02 9.40623760e-01 4.54627164e-02]
 [1.37290191e-02 9.26280379e-01 5.99905066e-02]
 [9.91705656e-01 8.24098382e-03 5.33089951e-05]
 [3.70895250e-05 7.60140568e-02 9.23948765e-01]
 [1.61355478e-03 4.92827803e-01 5.05558610e-01]
 [5.71975652e-05 1.96547553e-01 8.03395271e-01]
 [9.90037799e-01 9.88953467e-03 7.26682265e-05]
 [2.54382864e-02 9.27980006e-01 4.65817340e-02]
 [9.86245334e-01 1.35747120e-02 1.79975963e-04]
 [9.90715384e-01 9.22158919e-03 6.30657742e-05]
 [9.95849729e-01 4.13344754e-03 1.68498664e-05]
 [9.83558357e-01 1.62686538e-02 1.72998902e-04]
 [2.01811621e-04 2.41418645e-01 7.583795

In [ ]:
%%writefile requirements.txt
tensorflow
numpy
matplotlib

Writing requirements.txt
